### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by thulieu** [mplodowski/DynamicPDF#18]
I'm using window 7 and I had full permission but when I use preview button on templates backend it show message.

unlink(C:\Users\lvthu\AppData\Local\Temp/04
![untitled](https://cloud.githubusercontent.com/assets/9412688/16827397/7d6f87cc-49b0-11e6-8d6e-c646dd87335b.png)
b854edea2a8e08d8007d212360ace1): Permission denied

**Comment by geoffbeaumont** [comment]
Same on Windows 10, running under WampDeveloper Pro rather than XAMP, or under PHP built in webserver.

**Comment by mplodowski** [comment]
Hi,

this is an issue with dompdf library itself. It has been fixed in version 0.7.

https://github.com/dompdf/dompdf/pull/1096

My plugin is based on barryvdh/laravel-dompdf so I must wait for him to update his library first.

For now you can check this solution:

https://github.com/barryvdh/laravel-dompdf/issues/186#issuecomment-174359669

**Comment by mplodowski** [comment]
I updated plugin to use domPDF version 0.7. For now you will need to enable bleeding edge updates to update to version 2.1.1. You can do this by changing `config/cms` file and setting `edgeUpdates` to `true`.

Let me know if this resolves your problems.
